{
 "title": "Container Statistics",
 "description": "Dashboard to show container statistics with pod data of each container",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "Node", "query": "label_values(instance)" },
   { "name": "Container", "query": "label_values(container)" },
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Container Memory (Percent)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"\",container_name=~\"^$Container$\",namespace=~\"$Namespace\"}) / sum (machine_memory_bytes{instance=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Container Memory(size)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_name!=\"\",container_name=~\"^$Container$\",namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Container CPU Cores (Percent)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container_name=~\"^$Container$\",namespace=~\"$Namespace\"}[1m])) / sum (machine_cpu_cores{instance=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Container CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container_name=~\"^$Container$\",namespace=~\"$Namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Container Network Transmit Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_errors_total{container_name=~\"^$Container$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Container Pod Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{container_name=\"$Container\",namespace=~\"$Namespace\"}) by (pod_name))"
    }
   ]
  },
  {
   "title": "Cluster or Selected Node Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "All CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Container Network Recieve Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_errors_total{container_name=~\"^$Container$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Container Pod Status",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"^$Container.*\",namespace=~\"$Namespace\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{container_name=~\"^$Container$\",namespace=~\"$Namespace\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{container_name=~\"^$Container$\",namespace=~\"$Namespace\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Container Disk IO (Write/read)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{container_name=~\"^$Container$\",namespace=~\"$Namespace\"}[5m]))\r\n",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{container_name=~\"^$Container$\",namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Container Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Container Memory (PODS)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{container_name=\"$Container\",namespace=~\"$Namespace\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Container CPU Cores (PODS)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 19 },
   "targets": [
    {
     "expr": "(rate (container_cpu_usage_seconds_total{container_name=~\"^$Container$\",namespace=~\"$Namespace\"}[1m])) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Container Disk IO (Write/read)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(rate(container_fs_writes_bytes_total{container_name=~\"^$Container$\",namespace=~\"$Namespace\"}[5m]))\r\n",
     "legendFormat": "Received"
    },
    {
     "expr": "- (rate(container_fs_reads_bytes_total{container_name=~\"^$Container$\",namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(rate (container_network_receive_bytes_total{container_name=~\"^$Container$\",namespace=~\"$Namespace\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- (rate (container_network_transmit_bytes_total{container_name=~\"^$Container$\",namespace=~\"$Namespace\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}