{
 "title": "Jobs Usage",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total DataSeries",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(topk(20, count by (job)({__name__=~\".+\"})))"
    }
   ]
  },
  {
   "title": "DataSeries Per Job",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, count by (job)({__name__=~\".+\"}))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Top 20 Metrics",
   "type": "stat",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(20, count by (__name__)({__name__=~\".+\"}))"
    }
   ]
  }
 ]
}