{
 "title": "Docker containers monitoring",
 "description": "Using prom/container-exporter on WSL2 Ubuntu 20.04",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen[1m]))"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "targets": [
    { "expr": "rate(container_last_seen[1m])" }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_per_cpu_seconds_total{name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory usage per container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_stats{name=~\".+\", type=\"rss\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}