FROM praqma/network-multitool
RUN apk add --no-cache \
    python3 python3-dev py3-cryptography \
    gcc libffi-dev musl-dev \
    && python3 -m pip install --no-cache-dir --upgrade pip
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
